[package]
name = "rp2350-adc-protobuf"
version = "0.1.0"
edition = "2021"

[dependencies]
# Hardware Abstraction Layer
embassy-executor = { version = "0.10.0", features = ["platform-cortex-m", "executor-thread", "defmt"] }
embassy-rp = { version = "0.10.0", features = ["defmt", "rp235xa", "time-driver"] }
embassy-time = { version = "0.5.1", features = ["defmt"] }
# Serialization and Framing
prost = { version = "0.14.3", default-features = false, features = ["derive"] }
cobs = { version = "0.5.1", default-features = false }
# Embedded Utilities
defmt = "1.1.0"
defmt-rtt = "1.2.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
embedded-alloc = "0.7.0"
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"

[build-dependencies]
prost-build = "0.14.3"

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 'z'
overflow-checks = false
